name: "Bug Report"
description: "Create a bug report to help improve 3den Enhanced"
labels: [bug]
body:
    - type: textarea
        attributes:
            label: "Description"
            description: "A clear and concise description of what the bug is."
        validations:
            required: true
    - type: textarea
        attributes:
            label: "Steps To Reproduce"
            description: "Steps to reproduce the behavior."
            placeholder: |
                "1. Go to '....'
                2. Click on '....'
                3. Scroll down to '....'
                4. See the error"
        validations:
            required: false
    - type: textarea
        attributes:
            label: "Expected behavior"
            description: "A clear and concise description of what you expected to happen."
        validations:
            required: true
    - type: input
        attributes:
            label: "3den Enhanced Version"
            description: "What version of 3den Enhanced are you using?"
            placeholder: "X.X.X"
        validations:
            required: true
    - type: dropdown
        attributes:
            label: "Arma 3 Version"
            description: "What version of Arma 3 are you using?"
            options:
              - 2.16
              - 2.18
              - 2.20
              - 2.22
              - 2.24
              - 2.26
        validations:
            required: true
    - type: dropdown
        attributes:
            label: "Is the issue reproduceable?"
            options:
              - Always
              - Sometimes
              - Only once
    - type: checkboxes
        attributes:
            label: "Game breaking?"
            description: "Is this bug game breaking?"
            options:
                - label: "Yes"
                - label: "No"
    - type: textarea
        attributes:
            label:" Relevant Assets"
            description: |
                "A list of assets (logs, screenshots) relevant to this bug.

                Tip:
                - You can attach images or log files by clicking this area to highlight it and then dragging files in.
                - You can find your logfiles by pasting C:\Users\%USERNAME%\AppData\Local\Arma 3 into the address bar of your File Explorer."
