name: Feature Request
description: Have a good idea for a new feature? Let me know!
labels: [feature]
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the feature is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Use-Cases
      description: What use-cases do you have in mind?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Relevant Assets
      description: |
        A list of assets (logs, screenshots) relevant to this feature request.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
        You can find your logfiles by pasting C:\Users\%USERNAME%\AppData\Local\Arma 3 into the adress bar of your File Explorer