name: Translation Correction
description: Submit a request to change an existing translation
labels: [translation]
body:
    - type: input
        attributes:
            label: Translation Key
            description: To what key does the translation belong to?
            placeholder: STR_ENH_XXXXXXX
        validations:
            required: true
    - type: dropdown
        attributes:
            label: Language
            options:
                - Chinesesimp
                - Czech
                - English
                - French
                - German
                - Italian
                - Polish
                - Portuguese
                - Russian
                - Spanish
        validations:
            required: true
    - type: textarea
        attributes:
            label: Current Translation
        validations:
            required: true
    - type: textarea
        attributes:
            label: New Translation
        validations:
            required: true