name = "3den Enhanced"
mainprefix = "x"
prefix = "enh"
author = "R3vo"

[files]
include = [
    "LICENSE.md",
    "CONTRIBUTORS.md",
    "python_code/**",
    "keys/**"
]

[version]
major = 8
minor = 1
patch = 1
git_hash = 0

[hemtt.build]
optional_mod_folders = false

[hemtt.release]
archive = true

[properties]
author = "R3vo"
url = "https://steamcommunity.com/sharedfiles/filedetails/?id=623475643"

[lints.sqf.command_case]
severity = "Error"
options.ignore = [
    "AGLtoASL",
    "ASLtoAGL",
    "groupID"
]

[lints.sqf.banned_commands]
options.banned = [
    "execVM",
    "opfor",
    "blufor",
    "resistance",
    "and",
    "or",
    "not",
    "vehicle"
]

[lints.sqf.var_all_caps]
enabled = true

# Launched with `hemtt launch`
[hemtt.launch.default]

workshop = [
    "450814997",    # CBA_A3
    "1751569185",   # Pythia
    "1387934106",   # 7erra's Editing Extensions
    "2073243184",   # 3Den Stringtable Viewer
    "1231625987",   # Debug Console
    "463939057"     # ACE3
    # "2369477168"    # Advanced Developer Tools
]

parameters = [
    "-setThreadCharacteristics",
    "-limitFPS=60"
]

mission = "3denEnhanced.VR" # Mission to launch directly into the editor with
executable = "arma3_x64"

[hemtt.launch.spe]
extends = "default"

workshop = [
    "3117898674" # SPEX
]

dlc = [
    "spe",
]

[hemtt.launch.profiling]
extends = "default"

executable = "arma3profiling_x64.exe"
