name: Update Contributors

on: pull_request_target

jobs:
  update_contributors_msg:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-message: "Make sure to also update https://github.com/R3voA3/3den-Enhanced/blob/master/CONTRIBUTORS.md"
