# This is a basic workflow that is manually triggered

name: SQF to SQFC

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

jobs:
  windows:
    name: Windows

    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: arma-actions/sqfc@latest
        with:
          directory: "C:/Users/rober/OneDrive/Games/Arma 3/Arma 3 Mods/3den-Enhanced/"
